name: Build Docker Container

on:
  pull_request:
    branches:
      - main
      - master 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        # uncoment the row beewol to run only when the pull request is merged
        #if: github.event.pull_request.merged == true
      -
        name: Get Current Date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      -
      - name: Build Docker Image
        working-directory: ./docker_flaskapp
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/:${{ steps.date.outputs.date }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: $DOCKERHUB_USERNAME/:${{ steps.date.outputs.date }}
